test('change attribute')
test('add attribute')
test('remove attribtue')

test('change text node text')
test('remove text node')
test('change text node text within a div')
test('remove text node within a div')

test('replace multiple divs by 1 other div')
test('replace multiple divs by 1 text node')
test('replace multiple divs by multiple p')
test('replace first div by p')
test('replace last div by p')
test('replace middle div by p')

test('append div')
test('append text node')
test('prepend div')
test('prepend text node')
test('insert at div')
test('insert at text node')

test('change first div to text')
test('change first div to p')
test('change first div to p and migrate children')

test('remove last node')
test('remove first node')
test('remove middle node')
